FROM jboss/wildfly
MAINTAINER Didier Donsez

USER root 

#decommenter pour ajouter une datasource mysql
ADD customization /opt/jboss/wildfly/customization/
ADD modules /opt/jboss/wildfly/modules/

RUN mkdir $JBOSS_HOME/swagger

# si erreur ici du genre bin/bash^M... ===> Changer le format des fins de lignes du fichier en UNIX
RUN ["chmod", "+x", "/opt/jboss/wildfly/customization/execute.sh"]
RUN /opt/jboss/wildfly/customization/execute.sh

RUN /opt/jboss/wildfly/bin/add-user.sh admin Admin#70365 --silent
CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]

RUN chgrp -R 0 $JBOSS_HOME 
RUN chmod -R g+rw $JBOSS_HOME 

EXPOSE 8080
EXPOSE 9990
